version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=cifrados
      - POSTGRES_PASSWORD=ketchup123
      - POSTGRES_DB=proyecto1_cifrados
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  web:
    build: .
    command: python app.py
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

